'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useState, useEffect } from "react";
import LoadingScreen from "@/app/components/LoadingScreen";
// Configure fonts with more explicit options
const geistSans = localFont({
  src: [
    {
      path: './fonts/GeistVF.woff',
      style: 'normal',
    }
  ],
  display: 'swap',
  preload: true,
  fallback: ['system-ui', 'sans-serif'],
});

const geistMono = localFont({
  src: [
    {
      path: './fonts/GeistMonoVF.woff',
      style: 'normal',
    }
  ],
  display: 'swap',
  preload: true,
  fallback: ['monospace'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 2000); // Hide after 2 sec
  }, []);
    return (
      <html lang="en">
        <body className={`font-sans antialiased ${geistSans?.className || ''} ${geistMono?.className || ''}`}>
        {loading ? <LoadingScreen /> : children}
        </body>
      </html>
    );
  
}